### ISSUE TITLE
Task List | 1 º Desafio do Ignite 2022

### ISSUE THREAD

**Issue by ElisioWander** [ElisioWander/github-blog#4]
## 🏷️ Sobre 

**Todo**: Desafio proposto no primeiro modulo da trilha de React.js do Ignite.

O desafio proposto era:
- [x] Desenvolver a aplicação a partir do layout no Figma
- [x] Adicionar uma nova tarefa
- [x] Marcar e desmarcar uma tarefa como concluída
- [x] Remover uma tarefa da listagem
- [x] Mostrar a quantidade de tarefas 
- [x] Mostrar o progresso de conclusão das tarefas

### Adições além do desafio:
- [x] Salvar os dados no localStorage
- [x] Atualizar tarefa

---

## 🛠️ Tecnologias e serviços utilizados
Foram utilizadas as seguintes tecnologias para desenvolver a aplicação **Todo** :

- [HTML5](https://html.com/)
- [React.js](https://pt-br.reactjs.org/)
- [Typescript](https://www.typescriptlang.org/)
- [SASS](https://sass-lang.com/)

---

## 🗂️ Como baixar e iniciar o projeto 

```bash

    #clonar o projeto
    $ git clone https://github.com/ElisioWander/task-list.git

    #entrar no diretório
    $ cd todo

    #instalar as dependências
    $ npm install

    #iniciar a aplicação
    $ npm run dev
```
### Servidor local

localhost:3000

---

### 👤 Elisio Wander

- Linkedin: [@elisioWander](https://www.linkedin.com/in/elisio-wander-b88b69136/)
- Github: [@elisioWander](https://github.com/ElisioWander)
- Site: [elisiowander.vercel.app](https://elisiowander.vercel.app)
- Deploy: [todo-list](https://task-list-ch.vercel.app/)
